<?php
    $minhavar = "Adriano";
?>

<h1>Lista de Usuários</h1>
<hr>

<table class="table table-stripped">
    <thead>
        <th>Id</th>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Email</th>
        <th>Situação</th>
    </thead>
    <tbody>
        <?php foreach($usuarios as $usuario): ?>
        <tr>
            <td><?= $usuario->getId() ?></td>
            <td><?= $usuario->getNome() ?></td>
            <td><?= $usuario->getSobrenome() ?></td>
            <td><?= $usuario->getEmail() ?></td>
            <td><?= $usuario->getSituacao() ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>

<div class="buttons">
    <a class="btn btn-success" href="<?= $this->url('usuario', ['action'=>'adicionar']) ?>">Adicionar</a>
</div>

<style>
    .buttons {
        text-align: center;
    }
</style>
